In [1]:
from os import listdir
from os.path import isfile, join, exists
import pandas as pd
import io
import numpy as np
import re
import xlrd
from datetime import datetime

In [37]:
def pandas2csv(df,path):
    base_path = "/home/antarctic/Documents/OpenDat/Trabajo/"
    sep = ','
    index = False
    header = True
    encoding = 'latin-1'
    df.to_csv(base_path+path,
              index=index,
              sep=sep,
              header=header,
              encoding=encoding
              )

In [3]:
list_of_years=['1990','1992','1994','1996','1998','2000','2003','2006','2011']

In [33]:
df=pd.read_excel('/home/antarctic/Documents/OpenDat/Trabajo/1990/Desocupación por zona, según región y sexo.xls',skiprows=4)

In [34]:
df=df.iloc[1:,[0,1,2,3,5]]
df = df.rename(columns={'Unnamed: 0': 'REGION','Unnamed: 1':'DESOCUPACION','Unnamed: 2':'SEXO'})
df=df[~df.REGION.str.contains("Total País", na=False)] 
df=df[~df.REGION.str.contains("Fuente", na=False)] 
df=df[~df.SEXO.str.contains("Total", na=False)] 
df=df[~df.DESOCUPACION.str.contains("Total", na=False)] 
df=pd.melt(df, id_vars=['REGION','DESOCUPACION','SEXO'], value_vars=['Urbana','Rural'],var_name='ZONA', value_name='CANTIDAD')

In [35]:
for i in range(0,len(df)):
    if pd.isna(df.loc[i,'REGION'])==True:
        df.loc[i,'REGION']=df.loc[i-1,'REGION']
        
    if pd.isna(df.loc[i,'DESOCUPACION'])==True:
        df.loc[i,'DESOCUPACION']=df.loc[i-1,'DESOCUPACION']

In [36]:
df

    REGION DESOCUPACION    SEXO    ZONA CANTIDAD
0        I      Ocupado  Hombre  Urbana    67012
1        I      Ocupado   Mujer  Urbana    35445
2        I  Desocupados  Hombre  Urbana     6438
3        I  Desocupados   Mujer  Urbana     3602
4        I  Desocupados   Mujer  Urbana    39047
5       II      Ocupado  Hombre  Urbana    91576
6       II      Ocupado   Mujer  Urbana    33329
7       II  Desocupados  Hombre  Urbana     6985
8       II  Desocupados   Mujer  Urbana     3183
9       II  Desocupados   Mujer  Urbana    36512
10     III      Ocupado  Hombre  Urbana    46823
11     III      Ocupado   Mujer  Urbana    17969
12     III  Desocupados  Hombre  Urbana     3803
13     III  Desocupados   Mujer  Urbana     1013
14     III  Desocupados   Mujer  Urbana    18982
15      IV      Ocupado  Hombre  Urbana    72831
16      IV      Ocupado   Mujer  Urbana    35664
17      IV  Desocupados  Hombre  Urbana     7121
18      IV  Desocupados   Mujer  Urbana     3195
19      IV  Desocupados   Mujer  Urbana    38859
20       V      Ocupado  Hombre  Urbana   239325
21       V      Ocupado   Mujer  Urbana   131578
22       V  Desocupados  Hombre  Urbana    27567
23       V  Desocupados   Mujer  Urbana    19643
24       V  Desocupados   Mujer  Urbana   151221
25      VI      Ocupado  Hombre  Urbana    93215
26      VI      Ocupado   Mujer  Urbana    47154
27      VI  Desocupados  Hombre  Urbana     7254
28      VI  Desocupados   Mujer  Urbana     8871
29      VI  Desocupados   Mujer  Urbana    56025
..     ...          ...     ...     ...      ...
108   VIII  Desocupados   Mujer   Rural    19475
109     IX      Ocupado  Hombre   Rural    76126
110     IX      Ocupado   Mujer   Rural    14338
111     IX  Desocupados  Hombre   Rural     4728
112     IX  Desocupados   Mujer   Rural     1545
113     IX  Desocupados   Mujer   Rural    15883
114      X      Ocupado  Hombre   Rural   106136
115      X      Ocupado   Mujer   Rural    17471
116      X  Desocupados  Hombre   Rural     6013
117      X  Desocupados   Mujer   Rural     1109
118      X  Desocupados   Mujer   Rural    18580
119     XI      Ocupado  Hombre   Rural     5842
120     XI      Ocupado   Mujer   Rural     1426
121     XI  Desocupados  Hombre   Rural      621
122     XI  Desocupados   Mujer   Rural      115
123     XI  Desocupados   Mujer   Rural     1541
124    XII      Ocupado  Hombre   Rural     3136
125    XII      Ocupado   Mujer   Rural      714
126    XII  Desocupados  Hombre   Rural       84
127    XII  Desocupados   Mujer   Rural       14
128    XII  Desocupados   Mujer   Rural      728
129   R.M.      Ocupado  Hombre   Rural    52013
130   R.M.      Ocupado   Mujer   Rural    13926
131   R.M.  Desocupados  Hombre   Rural     1999
132   R.M.  Desocupados   Mujer   Rural     1110
133   R.M.  Desocupados   Mujer   Rural    15036
134   R.M.  Desocupados   Mujer   Rural   117930
135   R.M.  Desocupados  Hombre   Rural    40048
136   R.M.  Desocupados   Mujer   Rural     9806
137   R.M.  Desocupados   Mujer   Rural   127736

[138 rows x 5 columns]

In [39]:
listLines = []

def read_excel_files(folder):
    onlyfiles = [f for f in listdir(folder) if isfile(join(folder, f))]
    onlyfiles = filter(lambda x:x.endswith(("Desocupación por zona, según región y sexo.xls")), onlyfiles)
    
    for excel_file in onlyfiles:
        print(excel_file+year)
        df=pd.read_excel(folder+"/"+excel_file,skiprows=4)
        
        df=df.iloc[1:,[0,1,2,3,5]]
        df = df.rename(columns={'Unnamed: 0': 'REGION','Unnamed: 1':'DESOCUPACION','Unnamed: 2':'SEXO'})
        df=df[~df.REGION.str.contains("Total País", na=False)] 
        df=df[~df.REGION.str.contains("Fuente", na=False)] 
        df=df[~df.SEXO.str.contains("Total", na=False)] 
        df=df[~df.DESOCUPACION.str.contains("Total", na=False)] 
        df=pd.melt(df, id_vars=['REGION','DESOCUPACION','SEXO'], value_vars=['Urbana','Rural'],var_name='ZONA', value_name='CANTIDAD')
        for i in range(0,len(df)):
            if pd.isna(df.loc[i,'REGION'])==True:
                df.loc[i,'REGION']=df.loc[i-1,'REGION']
        
            if pd.isna(df.loc[i,'DESOCUPACION'])==True:
                df.loc[i,'DESOCUPACION']=df.loc[i-1,'DESOCUPACION'] 
        
        df['FECHA']='01-01-'+year
        
        listLines.append(df)
        output = pd.concat(listLines)
        output_path = "Desoc_zona.csv"
        pandas2csv(output,output_path)        
        
for year in list_of_years:
    folder = '/home/antarctic/Documents/OpenDat/Trabajo/'+year 
    read_excel_files(folder)

Desocupación por zona, según región y sexo.xls1990
Desocupación por zona, según región y sexo.xls1992
Desocupación por zona, según región y sexo.xls1994
Desocupación por zona, según región y sexo.xls1996
Desocupación por zona, según región y sexo.xls1998
Desocupación por zona, según región y sexo.xls2000
Desocupación por zona, según región y sexo.xls2006